//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppMinas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estructura
    {
        public int idEstructura { get; set; }
        public int idConexion { get; set; }
        public long idCampo { get; set; }
    
        public virtual Campo Campo { get; set; }
        public virtual Conexion Conexion { get; set; }
    }
}
