//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppMinas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FO2nIAoXvBZ
    {
        public int Codigo { get; set; }
        public string ID { get; set; }
        public string UBIPUEST { get; set; }
        public string FECHINS { get; set; }
        public string FECHINSPE { get; set; }
        public string Funcion { get; set; }
        public string OBS { get; set; }
        public string ALERTA { get; set; }
        public string Observaciones { get; set; }
        public string INGSALI { get; set; }
        public string OBS1 { get; set; }
        public string PRO { get; set; }
        public string OBS3 { get; set; }
        public string ESTARMA { get; set; }
        public string MUNICION { get; set; }
        public string CortedeCabello { get; set; }
        public string AFEITADA { get; set; }
        public string UNIFORME { get; set; }
        public string OBSE { get; set; }
        public string FOTOINSP { get; set; }
        public string FIRMAGUARDA { get; set; }
        public string FIRMAINSP { get; set; }
        public string Title { get; set; }
        public string CreatedOn { get; set; }
        public string UpdatedOn { get; set; }
        public string UserName { get; set; }
    }
}
