//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppMinas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Formulario1
    {
        public long idFormulario1 { get; set; }
        public long idLocacion { get; set; }
        public int idFormulario { get; set; }
        public string fechaCreacion { get; set; }
        public string fechaActualizacion { get; set; }
        public long idUsuario { get; set; }
        public string FECHA { get; set; }
        public string HORA { get; set; }
        public string TRAYEC { get; set; }
        public string OTROTRAY { get; set; }
        public string NOVEDAD { get; set; }
        public string DESCRIP { get; set; }
    
        public virtual Formulario Formulario { get; set; }
        public virtual Locacion Locacion { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
